default_language_version:
  python: python3.9

default_stages: [commit, push]
exclude: '^(?!git_rank/)'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: LICENSE

  - repo: local
    hooks:
      - id: git_rank_codestyle
        name: Check Git Rank codestyle
        entry: bash -c 'cd git_rank && make check-codestyle'
        types: [python]
        language: system
