server:
  host: "${SERVER_HOST}"
  port: ${SERVER_PORT}

logging:
  handlers:
    default:
      class: logging.StreamHandler
      level: DEBUG
      formatter: colored

    file_handler_info:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      filename: log/default.log
      formatter: plain
      encoding: utf8
      maxBytes: 10485760
      backupCount: 10

    file_handler_debug:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      filename: log/default-debug.log
      formatter: plain
      encoding: utf8
      maxBytes: 10485760
      backupCount: 10

  loggers:
    level: DEBUG
    handlers: [default, file_handler_info, file_handler_debug]
    propagate: True

  logger_levels:

git_remote:
  github:
    access_token: "${GITHUB_ACCESS_TOKEN}"
    api_url: "https://api.github.com"
    user_repo_relation: "owner" # all, member, owner
    results_per_page: 100
    
linters:
  python:
    arguments: "--disable=E0401"
  java:
    arguments: "-f text -R rulesets/java/quickstart.xml"
